config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'projects#index'
  resources :projects do
    member do
      get :add_user, :remove_user
    end
    resources :bugs do
      member do
        get :assign_developer
        get :change_status
      end
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bug.rb
# frozen_string_literal: true

class Bug < ApplicationRecord
  belongs_to :user
  belongs_to :project
  belongs_to :assignee, optional: true, class_name: 'User', foreign_key: 'assignee_id'

  mount_uploader :image, ImageUploader
end

app/models/dev.rb
# frozen_string_literal: true

class Dev < User
  has_and_belongs_to_many :projects, foreign_key: :user_id
  has_many :bugs, through: :projects
end

app/models/manager.rb
# frozen_string_literal: true

class Manager < User
  has_many :projects, foreign_key: :user_id
end

app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :users
  has_many :bugs, dependent: :destroy
end

app/models/qa.rb
# frozen_string_literal: true

class Qa < User
  has_and_belongs_to_many :projects, foreign_key: :user_id
  has_many :bugs, foreign_key: :user_id
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def manager?
    type == 'Manager'
  end

  def developer?
    type == 'Dev'
  end

  def qa?
    type == 'Qa'
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pundit

  after_action :verify_authorized, unless: :devise_controller?
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:type])
  end
end

app/controllers/bugs_controller.rb
# frozen_string_literal: true

class BugsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_bugs,  except: [:new, :create, :index, ]

  def new
    @project = Project.find(params[:project_id])
    @bug = Bug.new(project: @project)
    authorize @bug
  end

  def create
    @bug = current_user.bugs.build(bug_params)
    @project = Project.find(params[:project_id])
    @bug.project = @project
    authorize @bug
    if @bug.save
      redirect_to project_bugs_path(@project)
    else
      render 'new'
    end
  end

  def show
    authorize @bug
  end

  def index
    @bugs = policy_scope(Bug)
    @project = Project.find(params[:project_id])
    @devs = Dev.all
    @bugs = @bugs.where(project: @project)
    authorize Bug
  end

  def edit
    authorize @bug
  end

  def update
    authorize @bug
    if @bug.update(bug_params)
      redirect_to project_bug_path(@bug)
    else
      render 'edit'
    end
  end

  def assign_developer
    @project = Project.find(params[:project_id])
    authorize @bug
    @user = User.find(params[:user_id])

    if @user == current_user
      if @bug.update(assignee: @user)
        flash[:success] = 'Success'
      else
        flash[:alert] = 'Not Success'
      end
    end
    redirect_to project_bugs_path(@project)
  end

  def change_status
    @project = Project.find(params[:project_id])
    authorize @bug
    if @bug.update(status: 'Resolved')
      flash[:success] = 'Success'
    else
      flash[:alert] = 'Not Success'
   end
    redirect_to project_bugs_path(@project)
  end

  private

  def bug_params
    params.require(:bug).permit(:title, :date, :bug_type, :status, :image)
  end 

  def set_bugs
    @bug = Bug.find(params[:id])
  end
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_projects,  except: [:new, :create, :index ]

  def new
    authorize Project.new
  end

  def create
    @project = current_user.projects.build(project_params)
    authorize @project
    if @project.save
      redirect_to @project
    else
      render 'new'
    end
  end

  def index
    @projects = policy_scope(Project)
    authorize Project
  end

  def show
    authorize @project
  end

  def edit
    authorize @project
    @developers = Dev.all
    @users = User.all
    @qas = Qa.all
  end

  def update
    authorize @project
    if @project.update(project_params)
      redirect_to @project
    else
      render 'edit'
    end
  end

  def destroy
    authorize @project
    @project.destroy
    redirect_to projects_path
  end

  def add_user
    @user = User.find(params[:user_id])
    authorize @project 
    @project.users << @user
    redirect_to edit_project_path(@project)
  end

  def remove_user
    @user = User.find(params[:user_id])
    authorize @project 
    @project.users.delete(@user)
    redirect_to edit_project_path(@project)
  end

  private

  def project_params
    params.require(:project).permit(:title, :body)
  end

  def set_projects
    @project = Project.find(params[:id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/b_ugs_helper.rb
# frozen_string_literal: true

module BUgsHelper
end

app/helpers/bugs_helper.rb
# frozen_string_literal: true

module BugsHelper
end

app/helpers/project_helper.rb
# frozen_string_literal: true

module ProjectHelper
end

app/views/bugs/edit.html.erb
<h1>Edit  Bugs</h1>
<%= form_for :bug, url:  project_bug_path(@bug), method: :patch  do |f| %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field:title %>
  </p>

  <p>
    <%= label_tag 'Bug Deadline:' %></br>
    <%= f.date_field:date %>
  </p>

  <p>
    <%= label_tag 'Bug Type:' %></br>
    <%= f.radio_button :bug_type, 'Bug', :checked =>true %>Bug <br/>
      <%= f.radio_button :bug_type, 'Feature' %> Feature<br/>
  </p>

  <p>
    <%= label_tag 'Bug Status:' %></br>
    
    <%= f.select :status, options_for_select([["New"] ,["Started"] , ["Resolved"]]) %>
  </p>  

  <p>
    <%= f.submit "Edit Bug"%>
  </p>

<% end %>

app/views/bugs/index.html.erb
<h1>Listing Bugs</h1>
  <div class ="table-responsive">
    <table class ="table">
      <tr>
        <th>Bug Image</th>
        <th>Bug Title</th>
        <th>Bug Type</th>
        <th>Bug Status</th>
        <th>Bug Deadline</th>
        <th>Action</th>
        <th>Current Status</th>
      </tr>
    <% @bugs.each do |bug| %>
      <tr>
        <td><%= image_tag bug.image_url(:thumb) %></td>
        <td><%= bug.title %></td>
        <td><%= bug.bug_type  %></td>
        <td><%= bug.status %></td>
        <td><%= bug.date %></td>
    <!--<td><%= link_to 'Edit', edit_project_bug_path(@project,bug) %></td> -->
        <% if current_user.type == 'Dev'%>
          <% if (!(bug.assignee_id == current_user.id)) and !(@devs.ids.include?bug.assignee_id )%>
        
            <td><%= link_to 'Assign to me', assign_developer_project_bug_path(@project , bug , user_id: current_user.id) %></td>
            <td><%= bug.status %></td>
        
          <% elsif ((bug.assignee_id == current_user.id) || (@devs.ids.include?bug.assignee_id)) and bug.status == 'Resolved' %>
            <td><b>Assigned to <%= bug.assignee.email%></b></td>
            <td>Resolved !</td>

          <% elsif bug.assignee_id == current_user.id %>  
            <td><b>Assigned to <%= bug.assignee.email%></b></td>
            <td><%= link_to 'Mark as Resolved', change_status_project_bug_path(@project, bug ) %></td> 
          <% else %>
            <td><b>Assigned to <%= bug.assignee.email %></b></td>
            <td><%= bug.status %></td>
          <% end %>
        <% elsif  current_user.type =='Qa'  %>
            <td>---</td>
            <td><%= bug.status %></td>     
        <% end %>
      </tr>
  <% end %>
</table>
</div>

app/views/bugs/new.html.erb
<h1>Add Bugs</h1>
<%= form_for :bug,  url: project_bugs_path(@project), :html => {:multipart => true}  do |f| %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= label_tag 'Bug Deadline:' %></br>
    <%= f.date_field :date %>
  </p>

  <p>
    <%= label_tag 'Bug Type:' %></br>
    
    <%= f.radio_button :bug_type, 'Bug', :checked =>true, data: {behavior: "clickable"} %>Bug <br/>
      <%= f.radio_button :bug_type, 'Feature', data: {behavior: "clickable"} %> Feature<br/>
  </p>

  <p>
    <%= label_tag 'Bug Status:' %></br>
    
    <%= f.select :status, options_for_select([["New"] ,["Started"] , ["Resolved"]]) %>
  </p>  

  <p>
    <%= f.file_field :image %>
  </p>

  <p>
    <%= f.submit "Add Bug"%>
  </p>
<% end %> 

app/views/bugs/show.html.erb
<p>
  <strong>Title: </strong>
  <%= @bug.title %><br>
  <strong>Deadline: </strong>
  <%= @bug.date %><br>
  <strong>Status: </strong>
  <%= @bug.status %><br>
  <strong>Bug Type: </strong>
  <%= @bug.bug_type %><br>
  <%= image_tag @bug.image_url.to_s %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bugzilla</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

   <!-- Css and bootstrap files for table designing -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

    <%= stylesheet_link_tag    'https://stackpath.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css'  %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">BugZilla</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">

          <ul class="nav navbar-nav">
            <li><%= link_to 'Home', projects_path %></li>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <% if ProjectPolicy.new(current_user, Project).new? %> 
                <li><%= link_to 'Create Project', new_project_path %></li>
              <% end %>
             <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
             <% else %>
              <li><%= link_to 'Sign In',  new_user_session_path %></li>
              <li><%= link_to 'Sign Up',  new_user_registration_path%></li>
             <% end %>
          </ul>

        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class ="container">
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>

      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %> 
      <%= yield %>
    </div>

    
  </body>
</html>

app/views/projects/edit.html.erb
<h1>Edit  Projects</h1>
<%= form_for :project, url:  project_path(@project), method: :patch  do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field(:title,{:class => 'form-control'}) %>
  </p>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area(:body, {:class => 'form-control'}) %>
  </p>

  <p>
    <%= f.submit({:class => 'btn btn-primary'} )  %>
  </p>

<% end %>

<h1>Add Developers</h1>
<div class = "table-responsive">
<table class="table">
  <tr>
    <th>
        Email
    </th>
    <th>
        Status
    </th>
    <th>
        Actions
    </th>
    </tr>
<% @developers.each do |dev| %>
    
      <% if (@project.users.ids.include? dev.id) %>
      <tr bgcolor="#000000"> 
        <td> <%= dev.email.concat%> </td>        
        <td><b>Already Added !</b></td>
        <td><%= link_to 'Remove Developer', remove_user_project_path(@project , user_id: dev.id) %></td>
      </tr>
      <% else %>
        <tr>
          <td> <%= dev.email.concat%> </td>  
          <td><b>Not Added !</b></td>
          <td><%= link_to 'Add Developer', add_user_project_path(@project , user_id: dev.id) %></td>
        </tr> 
      <% end %>
  <% end %>
</table>
</div>

<h1>Add QAs</h1>
<div class = "table-responsive">
<table class="table">
  <tr>
    <th>
        Email
    </th>
    <th>
        Status
    </th>
    <th>
        Actions
    </th>
    </tr>
<% @qas.each do |qa| %>
      <% if !(@project.users.ids.include? qa.id) %>
        <tr>
          <td> <%= qa.email %> </td>
          <td><b>Not Added !</b></td>
          <td><%= link_to 'Add QA', add_user_project_path(@project , user_id: qa.id) %></td>
        </tr>
      <% else %>
        <tr bgcolor="#000000">
          <td> <%= qa.email %> </td>
          <td><b>Already Added</b></td>
          <td><%= link_to '  Remove Qa', remove_user_project_path(@project , user_id: qa.id) %></td>
        </tr>
      <% end %>
   </tr>
  <% end %>
</table>
</div>
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Listing Projects</h1>
<% @projects.each do |project| %>
  <div class = "well">
    <h3><%= project.title %></h3>
    <%= link_to "Read More",project_path(project), :class => 'btn btn-default' %>
    <% if project.users.ids.include?current_user.id and current_user.type == "Qa"%> 
        <%= link_to "Report Bugs" , new_project_bug_path(project), :class => 'btn btn-default' %>
        <%= link_to "View Bugs" , project_bugs_path(project), :class => 'btn btn-default' %>
    <% elsif project.users.ids.include?current_user.id and current_user.type == "Dev"%>
         <%= link_to "View Bugs" , project_bugs_path(project), :class => 'btn btn-default' %>
    <% end %>
  </div>
<% end %>

app/views/projects/new.html.erb
<h1>Add Projects</h1>
<%= form_for :project,  url: projects_path  do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field(:title,{:class => 'form-control'}) %>
  </p>

  <p>
    <%= f.label :Description %><br>
    <%= f.text_area(:body,{:class => 'form-control'}) %>
  </p>

  <p>
    <%= f.submit({:class => 'btn btn-primary'} )  %>
  </p>
  
<% end %>



  

app/views/projects/show.html.erb
<p>
  <strong>Title: </strong>
  <%= @project.title %>
</p>

<p>
  <strong>Description: </strong>
  <%= @project.body %>
</p>

<% if current_user == @project.user %>

  <%= link_to "Edit Project", edit_project_path(), :class => 'btn btn-default' %>

  <%= link_to "Delete Project", project_path() , method: :delete , :class => 'btn btn-danger', data: {confirm: "Are you sure ?"} %>
<% end %>

<br>
<br>

<%= link_to 'Back', projects_path %>